---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role aws
#
# Overview:
#
#
# Dependencies:
#
#
# Example play:
#
#

- name: create data directories
  file: >
    path={{ item }}
    state=directory
    owner=root
    group=root
    mode=0700
  with_items:
    - "{{ aws_data_dir }}"
    - "{{ aws_log_dir }}"

- name: create app directory
  file: >
    path={{ item }}
    state=directory
    owner=root
    group=root
    mode=0755
  with_items:
    - "{{ aws_app_dir }}"

